[package]
name = "relativistic-rt"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.13"
ndarray = "0.16.1"
num_cpus = "1.16.0"
rand = "0.8.5"
